site_name: NexusDI
site_description: A lightweight and powerful dependency injection framework for Python
site_author: Harrison Alonso Arroyave Gaviria
site_url: https://harrison-gaviria.github.io/nexusdi

repo_name: harrison-gaviria/nexusdi
repo_url: https://github.com/harrison-gaviria/nexusdi

theme:
  name: material
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src")
          options:
            docstring_style: google

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quick-start.md
    - Basic Concepts: getting-started/concepts.md
  - User Guide:
    - Lifecycle Management: guide/lifecycle.md
    - Dependency Injection: guide/injection.md
    - Component Scanning: guide/scanning.md
    - Scoped Dependencies: guide/scoped.md
    - Circular Dependencies: guide/circular.md
  - API Reference:
    - Core: api/core.md
    - Decorators: api/decorators.md
    - Exceptions: api/exceptions.md
    - Scanning: api/scanning.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Patterns: examples/advanced.md

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/harrison-alonso-arroyave-gaviria-4ba07b358
      name: Harrison Alonso Arroyave Gaviria

copyright: '&copy; 2025 Harrison Alonso Arroyave Gaviria.'
